services:

  seq:
    image: datalust/seq:latest
    container_name: seq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    
  testly-smtp-api:
    image: ${DOCKER_REGISTRY-}testlysmtpapi
    container_name: testly-smtp-api
    build:
      context: .
      dockerfile: src/Smtp/Testly.Smtp.Api/Dockerfile
    depends_on:
     - sqlserver