services:

  seq:
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  redis:
    ports:
      - "6379:6379"

  # testly-smtp-api:
  #   volumes:
  #     - ./data/smtp:/var/opt/smtp
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_HTTP_PORTS=8080
  #   ports:
  #     - "44310:8080"
  #     - "25:25" 