services:

  seq:
    image: datalust/seq:latest
    container_name: seq

  redis:
    image: redis:latest
    container_name: redis
    
  # testly-smtp-api:
  #   image: ${DOCKER_REGISTRY-}testlysmtpapi
  #   container_name: testly-smtp-api
  #   build:
  #     context: .
  #     dockerfile: src/Smtp/Testly.Smtp.Api/Dockerfile
  #   depends_on:
  #    - sqlserver